version: "3"

services:
  
  mongodb:
    image: mongo:4.0
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test123

  eosweb:
    image: eosio-explorer:latest
    ports: 
      - 3039:3039
      - 9615:9615
    restart: always
    links:
      - mongodb
    volumes:
      - ./config.js:/home/eosweb/config.js

